spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/clinicdb?authSource=admin
  # rabbitmq:
  #   host: rabbitmq
  #   port: 5672
  #   username: guest
  #   password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/.well-known/jwks.json
          
# queue:
#   name: name
  
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: DEBUG

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Servico de consultas e prontuarios.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Medio

