server:
  port: 8082
  
spring:
  application:
    name: clinic-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST_PORT:localhost:8888}
  cloud:
    config:
      profile: ${PROFILE:test}
  profiles:
    active: ${PROFILE:test}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

