spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest

  
# queue:
#   name: name

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springframework.security: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Servico de usuarios.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Alto