server:
  port: 8081
  servlet:
    context-path: /users/
spring:
  application:
    name: users-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST_PORT:config-server:8888}
  cloud:
    config:
      profile: ${PROFILE:test}
   